M48
; DRILL file {KiCad 8.0.1} date 2024-07-01T16:07:55-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-07-01T16:07:55-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0390
%
G90
G05
T1
X4.9852Y-4.5453
X4.9852Y-4.6634
T2
X4.4059Y-4.3917
X4.6059Y-4.3517
X4.6059Y-4.4317
M30
